server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Cliente
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/Cliente/**

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false